# K-近邻算法-knn

In [1]:
import numpy as np
import operator

In [2]:
def createdataset():
    group = np.array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
    labels = ['A', 'A', 'B', 'B']
    return group, labels

In [3]:
def classify0(inX, dataset, labels, k):
    dataset_size = dataset.shape[0]
    # (以下）距离计算
    diff_mat = np.tile(inX, (dataset_size, 1)) - dataset
    # print(np.tile(inX, (dataset_size, 1)))
    # print(diff_mat)
    sq_diff_mat = diff_mat**2
    # print(sq_diff_mat)
    sq_distances = sq_diff_mat.sum(axis=1)
    # print(sq_distances)
    distances = sq_distances**0.5
    # print(distances)
    sorted_dist_ind = distances.argsort()
    print(sorted_dist_ind)
    class_count = {}
    #（以下)选择距离最小的k个点
    for i in range(k):    # 从0到3，不包含3
        #        print(range(k))
        votellabel = labels[sorted_dist_ind[i]]
        class_count[votellabel] = class_count.get(votellabel, 0) + 1
    sorted_class_count = sorted(class_count.items(), key=operator.itemgetter(1), reverse=True)
    print(sorted_class_count)
    return sorted_class_count[0][0]

In [4]:
group, labels = createdataset()
print(group)
print(labels)
print(classify0([0, 0], group, labels, 3)) #预测结果

[[1.  1.1]
 [1.  1. ]
 [0.  0. ]
 [0.  0.1]]
['A', 'A', 'B', 'B']
[2 3 1 0]
[('B', 2), ('A', 1)]
B


In [5]:
def file2matrix(filename):
    fr = open(filename)
    arrayolines = fr.readlines()
    numberoflines = len(arrayolines)
    returnmat = np.zeros((numberoflines, 3))
    classlabelvector = []
    index = 0
    for line in arrayolines:
        line = line.strip()
        listfromline = line.split('\t')
        returnmat[index, :] = listfromline[0:3]
        classlabelvector.append(int(listfromline[-1]))
        index += 1
    return returnmat, classlabelvector

In [10]:
# 查看数据
datingDataMat, datingLabels = file2matrix('datingTestSet2.txt')
datingDataMat

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
       ...,
       [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
       [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
       [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]])

In [12]:
datingLabels[0:20]

[3, 2, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3]